main: cc.altoya.pluginname.App
name: pluginname
version: 0
folia-supported: true
api-version: 1.20
description: BLANK DESCRIPTION

commands:
  commandName:
    description: description
    usage: /command {var} {var}